kind: pipeline
name: default
steps:

  - name: docker
    image: plugins/docker
    settings:
      repo: ethicaljobs/aphex
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
      build_args: [ 'VERSION_TAG=${DRONE_TAG=latest}' ]
      tags:
        - 'latest'
        - '${DRONE_TAG=${DRONE_COMMIT=latest}}'

  - name: notify-slack
    image: plugins/slack
    settings:
      webhook: https://hooks.slack.com/services/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
      channel: deployments
